server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 20M;

    # /api/users → backend:8080/users
    # /api/posts → backend:8080/posts
    location /api/ {
        proxy_pass http://backend:8080/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # /uploads 경로는 제거하지 않고 그대로 전달
    location /uploads/ {
        proxy_pass http://backend:8080;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # React Router 주소로 직접 접속하거나 새로고침할 때 사용
    location / {
        try_files $uri $uri/ /index.html;
    }
}